### ISSUE TITLE
[question] How to use this lib with Redux?

### ISSUE THREAD

**Issue by abitdodgy** [geolessel/react-phoenix#13]
Still getting to grips with React in general, so excuse the question if it sounds silly. In most examples I've seen, a Redux store is passed to the component when rendering it inside the JS file.

```
React.renderComponent(<MyComponent state={someStateStoreFromRedux} />, document.body);
```

Given that `react-phoenix` lets us render components from our eex templates, how would I go about using it with a Redux store?

**Comment by scmx** [comment]
@abitdodgy Here's what I do:

```eex
<%= react_component "myApp.MyComponent", something: "initial state" %>
```

```javascript
function configureStore (initialState) {
  return createStore(...
}
```

```javascript
class MyComponent extends React.Component {
  constructor (props) {
    super(props)
    const initialState = props
    this.store = configureStore(initialState)
  }

  render () {
    return (
      <Provider store={this.store}>
        ...
      </Provider>
    )
  }
}
```
```javascript
window.myApp = {
  MyComponent
}
```

**Comment by scmx** [comment]
Hi @abitdodgy, did this solve your use case, can we close this?

**Comment by geolessel** [comment]
@abitdodgy I'm going to go ahead and close this and consider it answered. If it doesn't clear up your question, feel free to respond.

**Comment by abitdodgy** [comment]
@scmx that was indeed very helpful. Thank you for providing the example. @geolessel thanks!
