### ISSUE TITLE
Poison version with std_json_io_2

### ISSUE THREAD

**Issue by dweirich** [geolessel/react-phoenix#14]
I'm getting this message when doing `mix deps.get`

```
Failed to use "poison" (version 2.2.0) because
  arc (version 0.6.0) requires ~> 2.0 or ~> 3.0
  ecto (version 2.1.3) requires ~> 2.2 or ~> 3.0
  ex_aws (version 1.0.0) requires >= 1.2.0
  phoenix (version 1.2.1) requires ~> 1.5 or ~> 2.0
  react_phoenix (version 0.4.1) requires ~> 2.2 or ~> 3.0
  std_json_io_2 (version 0.2.0) requires ~> 3.0
  mix.lock specifies 2.2.0
```

Does std_json_io_2 need poison 3.0 or would an earlier release still work?

**Comment by scmx** [comment]
@geolessel Where's the source for https://hex.pm/packages/std_json_io_2, the github and hexdocs links are broken.
@dweirich Does it work if you specify `{:poison, "~> 2.2", override: true}`?

**Comment by dweirich** [comment]
@scmx Yup, that worked! Thanks.

**Comment by geolessel** [comment]
@scmx The github is at https://github.com/geolessel/std_json_io. I'll need to update that. Thankfully, the owner of the original `std_json_io` has added me as a contributor so I should be able to make changes in the original and make _it_ the dependency instead.

@dweirich Glad that worked. Thanks @scmx!
