### ISSUE TITLE
How to get it working in IE EDGE

### ISSUE THREAD

**Issue by dav11d** [geolessel/react-phoenix#16]
Copied everything from the video (https://www.youtube.com/watch?v=icwjAbck8yk)

Everything working fine in chrome/firefox but doesn't want to appear in IE EDGE,

I can see the Div in the dom explorer but nothing after that. 

Showing SCRIPT438: Object doesn't support property or method 'forEach' in the console.

Now I've tried using 'import babel-polyfill' in the top of my app.js , but then it doesn't render in chome/firefox and is still showing blank in IE edge.

Apologies if this is a babel/react set up issue, I'm new.

**Comment by scmx** [comment]
Please try this patch https://github.com/geolessel/react-phoenix/pull/4.
`{:react_phoenix, github: "scmx/react-phoenix", ref: "d1537be1855e9e555716c1380448337d8958140c"}`

**Comment by dav11d** [comment]
Still having the same issue I'm afraid

**Comment by scmx** [comment]
Make sure the updated package is used
`mix deps.clean react_phoenix && mix deps.get`
And make sure the updated npm package is used
`rm -rf node_modules/react-phoenix`
`npm install`
Or if phoenix 1.3
`(cd assets; rm -rf node_modules/react-phoenix)`
`(cd assets; npm install)`

**Comment by dav11d** [comment]
Thats the one, all working now 👍

**Comment by geolessel** [comment]
@dav11d @scmx That PR has been merged into master. I will work on cutting a new release as soon as I get a chance.
