### ISSUE TITLE
Not swapping in the Component

### ISSUE THREAD

**Issue by keslert** [geolessel/react-phoenix#29]
I've followed the instructions carefully, but my component isn't being swapped into the DOM. I've verified that the component is being compiled in priv/static/js/app.js and the DOM shows the following `<div data-react-class="Components.MyComponent" data-react-props="{}"></div>`.

Not sure what I'm missing... I'm using :react_phoenix "\~>0.5.1", :phoenix, "\~> 1.3.0", elixir: "\~> 1.4"

**Comment by scmx** [comment]
Hi, can you verify in the console that you have exposed your component as window.Components.MyComponent ?

**Comment by keslert** [comment]
Ahh... yep. I modified my default layout and forgot that I wasn't including this line anymore
`<script src="<%= static_path(@conn, "/js/app.js") %>"></script>`
Thanks for the help!

**Comment by geolessel** [comment]
That's exactly what I was going to suggest. Thanks for answering @scmx. Glad you got it figured out, @keslert.
