### ISSUE TITLE
Consider peer-dependency for react

### ISSUE THREAD

**Issue by hdra** [geolessel/react-phoenix#33]
Hi, some thoughts came to mind from recent error I had that was caused by the "root renderer" using different versions of react than the react components.

Since the setup assumes there is a `package.json` file for the frontend project, maybe its safe to assume that most people will have their own react project set up separately anyway (through `create-react-app` or whatever)? In that case, maybe we can consider having `react` as a `peerDependency` of the project so that we wouldn't have 2 separate versions of react running.

Also, since the project itself is a thin wrapper around react, maybe can also consider relaxing the version constraint (something like `>15`, or even `*`) so that users can decide which version of react to use with their own `package.json`.

**Comment by geolessel** [comment]
@hdra I'm very open to your suggestion. Could you work something up and submit a pull request?

**Comment by hdra** [comment]
👌I'll prepare something this coming weekend

**Comment by geolessel** [comment]
Thanks @hdra!
