### ISSUE TITLE
Webpack Error w/ Yarn

### ISSUE THREAD

**Issue by haydenrou** [geolessel/react-phoenix#50]
Error: "You may need an appropriate loader to handle this file type"

Elixir version: 1.10.3
Erlang version: 23.0
Phoenix version: 1.5.1

Using Yarn, I received the above error which was fixed by adding the below rule to my webpack.config.js file.

`        {
          test: /\.jsx$/,
          use: {
            loader: 'babel-loader'
          }
        }
`

I'm happy to submit a PR to the documentation for this, but I just wanted to check I wasn't missing something before I did so.

**Comment by jessejanderson** [comment]
@haydenrou thanks! I had this issue too and this fixed it. Should probably be added to the setup steps. 👍
